USE PALESTRA;

drop TABLE IF EXISTS ISCRITTO;
drop TABLE IF EXISTS CORSO;
drop TABLE IF EXISTS ISCRITTOCORSO;
drop TABLE IF EXISTS VISITA;
drop TABLE IF EXISTS PRENOTAZIONEVISITA;
drop TABLE IF EXISTS MACCHINARIO;
drop TABLE IF EXISTS MANUTENZIONEMACCHINARIO;


CREATE TABLE ISCRITTO
        ( CODICEBADGE INT primary key,
          NOME CHAR(14),
          COGNOME CHAR(14),
	  CF CHAR(20),
	  DATADINASCITA DATE,
	  DATAPRIMAISCRIZIONE DATE,
	  RINNOVO CHAR(3),
	  DATARINNOVO DATE,
	  TIPOABBONAMENTO CHAR(20));
	 
CREATE TABLE CORSO
        ( NOMECORSO CHAR(10) primary key,
          N_MAXISCRITTI INT,
          N_ISCRITTI INT,
          ISTRUTTORE CHAR(30));

CREATE TABLE ISCRITTOCORSO
        ( CODICEBADGE INT,
          NOMECORSO CHAR(10),
	  PRIMARY KEY (CODICEBADGE,NOMECORSO),
          FOREIGN KEY (CODICEBADGE) REFERENCES ISCRITTO(CODICEBADGE) -- ON UPDATE CASCADE 
);

CREATE TABLE VISITA
        ( NOMEVISITA CHAR(20) PRIMARY KEY,
          TIPOVISITA CHAR(20),
          MEDICO CHAR(30));

CREATE TABLE PRENOTAZIONEVISITA
        ( DATA DATE,
          ORA TIME,
	  CODICEBADGE INT,
	  NOMEVISITA CHAR(20),
	  MEDICO CHAR(30),
	  PRIMARY KEY (DATA,ORA),
	  FOREIGN KEY (CODICEBADGE) REFERENCES ISCRITTO(CODICEBADGE),
	  FOREIGN KEY (NOMEVISITA) REFERENCES VISITA(NOMEVISITA)
);

CREATE TABLE MACCHINARIO
        ( CODICEMACCHINARIO INT PRIMARY KEY,
          NOMEMACCHINARIO CHAR(20),
	  DATAACQUISTO DATE
);

CREATE TABLE MANUTENZIONEMACCHINARIO
        ( CODICEMACCHINARIO INT,
          DATAULTIMAMANUTENZIONE DATE,
          TIPOMANUTENZIONE CHAR(2),
	  PRIMARY KEY (CODICEMACCHINARIO,DATAULTIMAMANUTENZIONE),
	  FOREIGN KEY (CODICEMACCHINARIO) REFERENCES MACCHINARIO(CODICEMACCHINARIO)
);


       
         